Refactor conversation overview
lanis-mobile/lanis-mobile pull request #253
Opened 2024-08-29 21:16 UTC by kurwjan

2024-10-22 18:21 UTC, kurwjan commented
Bin hiermit glaube zufrieden. Eigentlich wollte ich die Suche und FAB in einzelne Widgets aufteilen, aber ohne Packages wie Riverpod ist der Code noch länger als davor und dazu zu komplex.

2024-10-22 21:29 UTC, alessioC42 commented
Hab mir den code noch nicht angesehen, aber würde eventuell nurnoch das "chat erstellen" ein bissen anpassen. Evtl schreibe ich da morgen ein custom komponente für oder so. Ich will das flutter_tagging_plus package irgendwie los werden.

2024-10-22 21:29 UTC, alessioC42 commented
Ansonnsten sehr nice

2024-10-23 07:36 UTC, alessioC42 requested changes
I honestly skipped over the UI pat of the code, but all in all it seems fine.

2024-10-23 07:36 UTC, alessioC42 commented on app/lib/client/client_submodules/conversations.dart
> +    return parse(username).querySelector("span")!.text.trim();
maybe use a regex, to improve performance here?

2024-10-23 07:36 UTC, alessioC42 commented on app/lib/client/fetcher.dart
> +  void supply(final List<OverviewEntry> content) {
I get what this function does, but I do not really get the name "Angebot" / "liefern" ?

2024-10-23 16:08 UTC, alessioC42 submitted a review, later dismissed

2024-10-23 17:09 UTC, Rajala1404 requested changes
If you hide/show chats, the Loading icon is not aligned in the center and is shifted a bit to the left, beside that I have no other complains.
![VideoCapture_20241023-190500.jpg](https://github.com/user-attachments/assets/4f556311-093a-456f-9b0c-cded52baf647)

2024-10-23 18:37 UTC, Rajala1404 approved these changes

2024-10-26 13:37 UTC, merged