Improve main "mein_unterricht" page by adding data types and refreshing the code UI
lanis-mobile/lanis-mobile pull request #273
Opened 2024-09-24 17:56 UTC by alessioC42

2024-09-27 17:44 UTC, Rajala1404 requested changes
An sich sieht das super aus. Aber bei den Hausaufgaben hat man irgendwie einen hellen strich drum herum (bei dem dunklen Teil) ich geh mal davon aus das das irgendwie damit zusammenhängt das das Dunklere widget über dem helleren gerendert wird und etwas zu klein ist um es komplett zu überdecken. Außerdem finde ich den Abstand zum Text unter den Hausaufgaben ein bisschen klein (kann aber so bleiben)
![Screenshot_20240927_193616.jpg](https://github.com/user-attachments/assets/7d02499f-0a58-49d3-8293-b598a89eade2)

Ich weiß jetzt nicht ob das einfach noch nicht implementiert ist oder es einfach nicht lädt aber der Anwesenheiten button zeigt einfach nur ein leeren Screen an wo nur Anwesenheiten steht.


Bei Stunden wo auch datein angezeigt werden zeigt jede datei (im Preview) ['Instance of LessonsFile'] und overflowed auch wenn der Name vom Kurs zu lang ist (wird jedoch nur im Debug modus angezeigt).
![Screenshot_20240927_194300.jpg](https://github.com/user-attachments/assets/a9eac411-e29e-47fb-9eda-a91a057e357c)

2024-09-27 21:32 UTC, kurwjan requested changes
Bisschen mehr Padding überall wäre auch schön, da die Tiles ziemlich vollgepackt sind.

Das Problem mit den leeren Anwesenheiten gab es noch immer und hab es jetzt auch gefixt ([20d9efe](https://github.com/lanis-mobile/lanis-mobile/pull/273/commits/20d9efe9184e538474afc907950a73bcac445686)). Dazu noch ein Case gefixt ,wenn eine Anwesenheit null ist, der Anwesenheit-Screen ausartet.

Das Hausaufgaben Icon finde ich mit dem Checkmark unpassend, weiß aber auch nicht ob das alte besser ist.

Ich persöhnlich würde die ListTiles auch gleich durch Columns ersetzen, da die Features nicht wirklich benutzt werden.

Um noch den Feedbackburger ohne oberen Pattie und Bun zu beenden: Ich finds viel besser als vorher, dazu kann ich auch dauerhaft in rot sehen, wann ich geschwänzt hätte. Ich glaube ich mach mal auch ein paar Commits.

2024-09-27 22:09 UTC, kurwjan commented
> An sich sieht das super aus. Aber bei den Hausaufgaben hat man irgendwie einen hellen strich drum herum (bei dem dunklen Teil) ich geh mal davon aus das das irgendwie damit zusammenhängt das das Dunklere widget über dem helleren gerendert wird und etwas zu klein ist um es komplett zu überdecken.... ![Screenshot_20240927_193616.jpg](https://private-user-images.githubusercontent.com/115874847/371627495-7d02499f-0a58-49d3-8293-b598a89eade2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NzUwMzYsIm5iZiI6MTcyNzQ3NDczNiwicGF0aCI6Ii8xMTU4NzQ4NDcvMzcxNjI3NDk1LTdkMDI0OTlmLTBhNTgtNDlkMy04MjkzLWI1OThhODllYWRlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QyMjA1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmZkOThmOGMxZTFmMTRhNzFiNjk3NjJlMmUxNDY0NjAzYjExZWMwMTU1ZDk1MDQwNzM2NzFiNWMwYWM4Yzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fCzHnXdcNdXlZ-l3Gg1JqCWjZuI-ksTnxm-0TBjpeWM)

Man könnte es villt. fixen wenn man einen Stack benutzt, anstatt einen Container als Parent zu benutzen.

2024-09-28 09:03 UTC, alessioC42 commented
Ich denke, dass das Abwesenheitsschild angezeigt werden sollte. Es ist eine Erinnerung, dass die Stunde entschuldigt werden muss und es sollte nicht verschwinden, solange die Stunde noch offen ist. Sonst könnte es der Schüler verpassen. Ich finde dieses Symbol intuitiver. Es sagt "Aufgabe" und nicht "Schule".

2024-09-28 09:35 UTC, Rajala1404 requested changes
Also die meisten Bugs sind jetzt gefixt aber bei der letzten Stunde in Main Unttericht (ganz Unten) kann man weder Datum noch dateien Anzahl sehen da das vom Anwesenheiten Button überdeckt wird es seiden man scrollt ganz genau um zwischen den Gap von Button und Navigations Bar zu kommen
![Screenshot_20240928_113320.jpg](https://github.com/user-attachments/assets/90783882-6797-4469-96eb-6336ef1fb6a5)

Außerdem finde ich das der Anwesenheiten tab zu wenig padding hat weil das alles irgendwie zusammen gequetscht wird.

2024-09-28 16:11 UTC, kurwjan approved these changes
Hab Padding bisschen geändert, ist das so ok?
Außerdem kann man beim letzten Tile auch alle Daten sehen.

2024-09-29 16:29 UTC, Rajala1404 approved these changes
Hab keine Beschwerden. Keine Bugs gefunden und sieht gut aus. Approved

2024-09-29 16:39 UTC, merged