Configure settings through environment variables.
lanis-mobile/lanis-mobile pull request #274
Opened 2024-09-24 21:39 UTC by kurwjan

Fix  #264

How?

### Method 1: config file
Copy `template_config.json` and put it somewhere safe, or not. Adjust it and attach `--dart-define-from-file=PATH_TO_YOUR_COPY` to your run args.

### Method 2: pass everything through the run args.
Example:
`--debug --dart-define ID="6091"`, quotation marks are optional. I guess you could use $ENV_STUFF here.
For other arguments see `template_config.json`.

### Method 3: both?
You can provide a file and later disable it with the argument  `--dart-define DISABLE_OVERWRITE=true`

2024-09-26 04:27 UTC, Rajala1404 submitted a review, later dismissed
Sieht super aus

2024-09-28 09:18 UTC, alessioC42 requested changes
Moving the Storage initialization should break the background service. Haven't tested it, but it should not work anymore with this update.

2024-09-28 13:41 UTC, kurwjan commented
> Moving the Storage initialization should break the background service. Haven't tested it, but it should not work anymore with this update.

Ne funktioniert bei mir, hab aber auch nur diesen Debug Knopf getestet, der die Benachrichtigung forced.
`await globalStorage.initialize();` ist ja vor `await initializeNotifications();
  await setupBackgroundService();`.

2024-09-29 08:30 UTC, alessioC42 commented
> hab aber auch nur diesen Debug Knopf getestet

Das ist nicht das selbe. 
Im background service wird die "main" Methode ja garnicht ausgeführt. Die Inizialisierung muss auch in dem Background service statt finden. Der Notification button ist da etwas anders.

2024-09-29 10:55 UTC, kurwjan commented
> > hab aber auch nur diesen Debug Knopf getestet
> 
> Das ist nicht das selbe. 
> Im background service wird die "main" Methode ja garnicht ausgeführt. Die Inizialisierung muss auch in dem Background service statt finden. Der Notification button ist da etwas anders. 

ahhhh jetzt verstehe ich es.

2024-10-01 12:39 UTC, alessioC42 approved these changes

2024-10-01 12:40 UTC, merged