Development
lanis-mobile/lanis-mobile pull request #304
Opened 2024-11-19 16:08 UTC by alessioC42

2024-12-04 09:47 UTC, alessioC42 commented
@kurwjan , I am pretty sure, that I broke parts of the Notification system with the new CombinedAppletBuilder, but since I do not use it I also do not really know how it should behave. Would be great if you looked into that and fixed the applet. 

I removed the current filtering logic on behalf of creating a new one or integrating the existing system differently later before the launch of 3.0.0

Background services are also currently not fully implemented. This PR sets a new base other PRs can build uppon. For example the notification feature for the "Messages" or "Lessons" applet.

2024-12-04 14:31 UTC, kurwjan requested changes
Some small things:
![image](https://github.com/user-attachments/assets/0d1ef325-a623-4003-a1f9-62136506af9c)
+ Colors are in small case and there's a missing divider between dynamic color and app colors.
![image](https://github.com/user-attachments/assets/4617d7f0-5e2d-4caa-a557-9e6757454706)
+ There's an abundant divider on the top (looks weird to me). Also the timetable applet doesn't have a selected icon.
+ In dark mode the account switcher button is a bit too dark
+  Add account button should be replaced with a FAB
+ In notifications green tick should be a primary color tick
+ Maybe add a divider between "Alle Anwesenheiten" and the rest, currently it's only more elevated than the rest which is difficult to see in dark mode.
+ Yep conversations isn't correctly working anymore (not updating stuff like setting the unread alert)

The rest is fantastic. The current project organisation and database is much better. I love the new offline applet selector (I need to investigate it more) and the CombinedAppletBuilder.

2024-12-04 14:31 UTC, kurwjan commented on app/lib/view/settings/subsettings/notifications.dart
> +            FutureBuilder<int>(
Add forgotten check

2024-12-09 18:09 UTC, Rajala1404 approved these changes
Besides the Back button (that i already fixed) and the translation of Exception causes i have nothing to complain

2024-12-09 20:25 UTC, kurwjan approved these changes
Ich aktzeptiere das mal bevor ich es zu lang ziehe

2024-12-09 20:49 UTC, merged