Moddle Login with Dio
lanis-mobile/lanis-mobile pull request #320
Opened 2024-12-23 15:50 UTC by kurwjan

+ Login with Dio
+ Display error on top of WebView
   + Should support every platform than displaying the error under the WebView
+ Display no internet warning
+ Switch  `LessonsFile` with `FileInfo` and put it in `file_operations.dart` instead of being a part of Lessons.
+ Display file modal when downloading smth.
+ Copy error url when in error screen

2024-12-23 17:51 UTC, Rajala1404 requested changes
Internet warning does not get shown in File Storage.
And for some reason everything there is German (but i fix that in my UX PR)
![image](https://github.com/user-attachments/assets/7eaecb6f-d031-432f-bf74-fce7ddfc1581)

2024-12-23 17:56 UTC, kurwjan commented
> Internet warning does not get shown in File Storage.
> And for some reason everything there is German (but i fix that in my UX PR)
> ![image](https://github.com/user-attachments/assets/7eaecb6f-d031-432f-bf74-fce7ddfc1581)
> 

No internet warning in webview, not file storage.

2024-12-23 18:01 UTC, Rajala1404 submitted a review, later dismissed
Ah ok

2024-12-26 11:27 UTC, alessioC42 commented on app/lib/view/moodle.dart
> +  Future<void> getCookies() async {
I see pain.

2024-12-26 11:33 UTC, alessioC42 approved these changes

2024-12-26 11:33 UTC, merged